import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const N8N_BRAND_COLOR = '#ff6d5a';
export const N8N_DARK_COLOR = '#e55a4a';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: N8N_BRAND_COLOR,
    primaryContainer: '#ffdad4',
    secondary: '#775650',
    secondaryContainer: '#ffddda',
    tertiary: '#705c2e',
    tertiaryContainer: '#fcdf9e',
    surface: '#ffffff',
    surfaceVariant: '#f5dedb',
    background: '#fffbff',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#2d1511',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#2d1513',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#251a00',
    onSurface: '#201a19',
    onSurfaceVariant: '#534341',
    onBackground: '#201a19',
    onError: '#ffffff',
    onErrorContainer: '#410002',
    outline: '#857371',
    outlineVariant: '#d8c2be',
    inverseSurface: '#362f2d',
    inverseOnSurface: '#fbeeeb',
    inversePrimary: '#ffb4a6',
    elevation: {
      level0: 'transparent',
      level1: '#fff0ee',
      level2: '#fce8e5',
      level3: '#ffe0dc',
      level4: '#ffddd8',
      level5: '#ffd7d2',
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: N8N_DARK_COLOR,
    primaryContainer: '#5d1f18',
    secondary: '#e7bdb7',
    secondaryContainer: '#5d403c',
    tertiary: '#dbc386',
    tertiaryContainer: '#574519',
    surface: '#201a19',
    surfaceVariant: '#534341',
    background: '#201a19',
    error: '#ffb4ab',
    errorContainer: '#93000a',
    onPrimary: '#442925',
    onPrimaryContainer: '#ffdad4',
    onSecondary: '#442927',
    onSecondaryContainer: '#ffddda',
    onTertiary: '#3d2e05',
    onTertiaryContainer: '#fcdf9e',
    onSurface: '#ebe0de',
    onSurfaceVariant: '#d8c2be',
    onBackground: '#ebe0de',
    onError: '#690005',
    onErrorContainer: '#ffdad6',
    outline: '#a08c89',
    outlineVariant: '#534341',
    inverseSurface: '#fbeeeb',
    inverseOnSurface: '#201a19',
    inversePrimary: '#8c4d44',
    elevation: {
      level0: 'transparent',
      level1: '#2a2322',
      level2: '#342b2a',
      level3: '#3e3332',
      level4: '#423736',
      level5: '#4a3d3c',
    },
  },
};

export type AppTheme = typeof lightTheme;
